#### somni.dotfiles.linux ####
## PipeWire  Configurations ##

context.properties = {
  ### Core settings
  link.max-buffers = 32
  log.level        = 1
  core.daemon      = true
  core.name        = pipewire-0

  ### DSP settings
  default.clock.rate          = 96000
  default.clock.allowed-rates = [ 44100, 48000, 96000, 192000 ]
  default.clock.quantum       = 1024
  default.clock.min-quantum   = 256
  default.clock.max-quantum   = 8192
}
